### ISSUE TITLE
Add support for drf-spectacular

### ISSUE THREAD

**Issue by enzofrnt** [Horou/djangorestframework-deepserializer#5]
[drf-spectacular](https://github.com/tfranzel/drf-spectacular) is greate wagger generator and need to support this module.

refer to [this issue](https://github.com/tfranzel/drf-spectacular/issues/1201)

**Comment by Horou** [comment]
can you send me the error that you got

**Comment by enzofrnt** [comment]
> can you send me the error that you got

There is no error.
The description of the endpoint form deepview are wrong

**Comment by tfranzel** [comment]
@enzofrnt if you want to contribute or be helpful in any capacity, you need to learn to articulate your issues. One sentence, vague statements with lots of lazy typos do not encourage anyone to help you. People are more willing to help if they can see that you tried to the best of your ability. Take your time to lay out the issue and describe exactly what the problem is, including an example or demonstration. 

People invest countless hours of unpaid work into open source. The least you can do is put some effort in properly writing up your request.

**Comment by enzofrnt** [comment]
@tfranzel Yes, sorry, I didn't have time to explain.

So here is more information.

With this module, we are able to creating nested model directly from the original model serialize by creating a json file.

In most use cases, we will do something like that

```py

#Create nested model

{
   "id" = 66
   "fields" = "fields"
}

# And crete the original model

{
   "id" = 1
   "fields" = fields
   "forgeinkey_nested_model" = 66
}
```

But here with, djangorestframework-deepserializer we are able to do this :

```py
{
   "id" = 1
   "fields" = fields
   "nested_model" = {
      "id" = 66
       "fields" = "fields"
   }
}
```

And every thing will be made in one time
.
But, the [drf-spectacular](https://github.com/tfranzel/drf-spectacular) only display the original way.

**Comment by enzofrnt** [comment]
Error, sorry.
